### ISSUE TITLE
On Windows systems it doesn't work

### ISSUE THREAD

**Issue by frifix** [rubiojr/omnivore-exporter#2]
Hi,

I try to run this exporter on a Windows system. It exports only one article. Here is the console output:
```
C:\Backup> omnivore-exporter export --output-dir .
Exporting all articles except those with labels: [omnivore-exporter-skip Newsletter RSS]
Using: obelisk
Search query: in:all -label:omnivore-exporter-skip AND -label:Newsletter AND -label:RSS sort:saved
Exporting to folder . ...
* Exporting 'I've been using Neovim for the past six months. Here's what I learned'...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xdd5b96]

goroutine 1 [running]:
main.fileExists({0xc000b7c370?, 0xc000025180?})
        C:/Users/go/pkg/mod/github.com/rubiojr/omnivore-exporter@v0.1.1/main.go:224 +0x56
main.exportAll(0xc00003e780)
        C:/Users/go/pkg/mod/github.com/rubiojr/omnivore-exporter@v0.1.1/main.go:197 +0x8bc
github.com/urfave/cli/v2.(*Command).Run(0xc00022c000, 0xc00003e780, {0xc00002cf00, 0x3, 0x3})
        C:/Users/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x7e2
github.com/urfave/cli/v2.(*Command).Run(0xc00022c2c0, 0xc00003e6c0, {0xc00003e0c0, 0x4, 0x4})
        C:/Users/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272 +0xa65
github.com/urfave/cli/v2.(*App).RunContext(0xc00022a000, {0xf5d278, 0x133e660}, {0xc00003e0c0, 0x4, 0x4})
        C:/Users/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x58b
github.com/urfave/cli/v2.(*App).Run(...)
        C:/Users/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311
main.main()
        C:/Users/go/pkg/mod/github.com/rubiojr/omnivore-exporter@v0.1.1/main.go:124 +0x672
```
It would be great to be able to use the omnivore-exporter to export all articles before they will be deleted from the omnivore service.

**Comment by rubiojr** [comment]
Hi @frifix, I'm afraid I don't use Windows and have no plans to fix Windows related issues, because testing it would be hard for me.

Having said that, I'll have a closer look and see if something jumps out that I can easily fix without testing there.

**Comment by rubiojr** [comment]
@frifix did you try their exporter? https://docs.omnivore.app/using/exporting.html

**Comment by frifix** [comment]
@rubiojr thank you for your replay. After writing this issue I came across about this topic in the omnivore documentation and I have successfully exported my articles. In that case, I am closing this issue. Best regards.
